import { pathfindToCoordinates } from "./skills/pathfind-to-coordinates";
import { Skill } from "./types";
import type { Bot } from "mineflayer";

// IMPORTANT: Skills docs are autogenerated by parsing this file. Therefore, how this file
// _can_ be formatted is tightly coupled to to the generation logic in `skills_docs.py`.

export function buildSkillsRegistry(bot: Bot): Record<string, Skill> {
  return {
    /**
     * Pathfinds to a set of coordinates (digging and bridging as needed), stopping early if
     * something from the stopIfFound list becomes visible in the bot's surroundings.
     * @param coordinates - The target coordinates as an array ordered [x, y, z].
     * @param stopIfFound - An array of strings representing the names of things to stop at if found.
     */
    pathfindToCoordinates: async (
      coordinates: [number, number, number],
      stopIfFound: string[]
    ) => {
      return await pathfindToCoordinates(bot, coordinates, stopIfFound);
    },
  };
}
